version: '3'

services:
  mobile:
    privileged: true
    image: mobile:latest
    build:
      context: ./front/mobile
      dockerfile: ./Dockerfile
    volumes:
      - apk-volume:/apk

  server:
    build: ./server/
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/area"

  web:
    privileged: true
    build: ./front/web/
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./front/web/src
        target: /app/src
      - apk-volume:/app/public/apk
    depends_on:
      - mobile
      - server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  apk-volume:
