name: Create Feature Branches

on:
  issues:
    types: [opened]

jobs:
  createBranch:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, '[AUTOBRANCH]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create branch for task
        run: |
          TITLE="${{ github.event.issue.title }}"
          
          # Extract prefix and branch name
          PREFIX=$(echo "$TITLE" | grep -oP '\[AUTOBRANCH\]\[\K[^]]+')
          BRANCH_NAME_PART=$(echo "$TITLE" | sed -e 's/\[AUTOBRANCH\]\[\([^]]*\)\] //')
          
          # Construct final branch name
          BRANCH_NAME="${PREFIX}-${BRANCH_NAME_PART}"
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
